-- Migration: 0070_meal_recipes_reload_part6
-- Target: Cloudflare D1 (SQLite)
-- Part 6/6 of a full reload of meal_recipes from a licensed
-- external recipe dataset the user holds rights to use (raw_recipes.json,
-- confirmed 2026-08-08). Replaces the previous 141 self-authored recipes.
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-tom-tron-bong-cai', 'Tôm trộn bông cải', 'Tôm trộn bông cải thanh mát, giàu canxi, giúp ngăn ngừa bệnh ung thư, món ăn bổ dưỡng, ngon miệng, nhanh gọn, phù hợp cho bữa ăn gia đình mỗi ngày.', 'Sơ chế:
1. Tôm rửa sạch, lấy chỉ lưng, luộc chín trong nước sôi có nêm 1/2m muối, bóc bỏ vỏ.
2. Bông cải tách ra, rửa sạch, cắt miếng nhỏ, chần sơ, vớt ra ngâm vào nước đá, để ráo, để riêng bông và cọng.
3. Củ hành tây cắt múi cao, trộn với 1m đường.
4. Ngò tây 2 cây băm nhỏ, 1 cây để trang trí.

Thực hiện:
1. Tôm ướp với 1/3m tiêu, 1/2m nước cốt chanh, 2m tương ớt và ngò tây băm, trộn tôm với cọng bông cải và 3M xốt mayonnaise Aji-mayo®. Đun nóng 1m dầu ăn, cho 1M xả băm, 1M ớt băm cho tôm vào xào cho chín kỹ.', 1, 0, 0, 0, 0, NULL, 'Xếp bông cải xanh ra dĩa, cho tôm trộn vào giữa, trang trí với ngò tây.', 'Khi luộc bông cải cho them ít muối để bông cải đậm đà hơn. Luộc rau củ vừa chín tới để giữ độ giòn và màu xanh rau củ. Ướp tôm với tương ớt, chanh và ngò tây băm nhỏ giúp giảm mùi tanh của hải sản.', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('7c714575-dc92-413b-8caf-1186c4c91e85', 'recipe-tom-tron-bong-cai', NULL, '- Tôm đất tươi', 300, 'g', NULL, '- Tôm đất tươi: 300g', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('71a572e4-51bf-4676-80ad-8dc60c42ce71', 'recipe-tom-tron-bong-cai', NULL, '- Bông cải xanh', 300, 'g', NULL, '- Bông cải xanh: 300g', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('5ff4e137-879b-42ab-9ed5-04778f34af46', 'recipe-tom-tron-bong-cai', NULL, '- Ngò tây', 3, 'cây', NULL, '- Ngò tây: 3 cây', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('8b03f52d-bfc4-4779-9250-b28a9855d113', 'recipe-tom-tron-bong-cai', NULL, '- Tương ớt, tiêu, chanh', 1, '', NULL, '- Tương ớt, tiêu, chanh', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('4e04628c-604f-40d9-af4c-809b152a06df', 'recipe-tom-tron-bong-cai', NULL, 'Xốt Mayonnaise Aji-mayo® Vị Nguyên Bản', 1, '', NULL, 'Xốt Mayonnaise Aji-mayo® Vị Nguyên Bản', 4);
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-vit-quay-bac-kinh-chay', 'Vịt quay Bắc Kinh chay', 'Vịt quay Bắc Kinh chay với lớp da giòn, vị đậm đà, thích hợp cho ngày Rằm hoặc Trung thu, giúp bữa cơm chay thêm đặc biệt và hấp dẫn hơn bao giờ hết.', 'Sơ chế:
1. Pha xốt ướp: 1/2 chén nước, 1M nước tương “Phú Sĩ”, 2,5M hạt nêm Aji-ngon® từ nấm hương và hạt sen, 1/3M tiêu xay, 1m gừng băm, 1M hành boa-rô phi, 1M rượu mai quế lộ, 1M mật ong, 2M ngũ vị hương, trộn đều.
2. Cho đậu hũ vào hỗn hợp xốt để ướp cho thấm gia vị. Vớt ra để ráo. Giữ lại phần xốt ướp.

Thực hiện:
1. Cho 1M dầu ăn, 1M boaro phi, cho các loại nấm vào áp chảo, sau đó thêm 2M nước xốt ướp.
2. Trải miếng tàu hủ ky, rắc lên 1 ít bột năng. Lần lượt trải đều theo từng lớp, đậu hủ trắng mặt chiên vàng để ngoài áp vào miếng tàu hủ ki và mặt trắng lên trên, thêm nấm đùi gà, nấm đông cô, nấm kim châm, sau đó thêm 1 miếng đậu hủ đặt lên trên. Gói kín và chặt các nguyên liệu thành khối hình chữ nhật. Phết màu điều lên lớp vỏ bên ngoài.
3. Chiên áp chảo cho vàng giòn và các thành phần kết dính lại.
4. Đun sôi 3M nước, 1M xốt xá xíu chay, 1m dầu hào chay, trộn đều cho đến khi hơi sệt lại, rưới lên lớp da vịt chay.', 1, 0, 0, 0, 0, NULL, 'Dùng với cơm hoặc bánh mì.', 'Ướp đậu hủ trong xốt để đậu hủ thật thấm gia vị.
Áp chảo nấm để nấm giữ độ dai, độ ngọt và không ra nước.', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('57ce934b-7299-42f4-92de-dbe46e157632', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Đậu hũ chiên, cắt đôi theo chiều dọc', 2, 'miếng', NULL, 'Đậu hũ chiên, cắt đôi theo chiều dọc 2 miếng', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('9e3bd945-1225-4772-a85d-d6dfda4db44b', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Tàu hủ ky ngâm mềm', 3, 'miếng', NULL, 'Tàu hủ ky ngâm mềm: 3 miếng', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('2670ad4c-bf1d-433b-acfd-9d430ff3dc55', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Nấm đông cô tươi', 6, 'cái', NULL, 'Nấm đông cô tươi: 6 cái', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3405461e-19e5-42a2-9b81-4e489b78b82c', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Nấm đùi gà', 1, 'cây', NULL, 'Nấm đùi gà: 1 cây', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('6e3fbed5-367f-4ba1-b3ca-ab4325ce96f8', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Nấm kim châm', 80, 'g', NULL, 'Nấm kim châm: 80g', 4);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('0c4471db-35e7-4297-910e-8cae61323fd9', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Xốt xá xíu chay', 1, 'M', NULL, 'Xốt xá xíu chay: 1M', 5);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('fa975714-a807-4f23-b492-2d5e28cefc5e', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Hành boaro phi, gừng băm', 1, '', NULL, 'Hành boaro phi, gừng băm', 6);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('4036fa0c-0dd5-4e0c-8c7b-bfe9253b9b07', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Mật ong, rượu mai quế lộ, dầu hào chay', 1, '', NULL, 'Mật ong, rượu mai quế lộ, dầu hào chay', 7);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('6dfb57e0-1714-40c4-a954-2d5ec07feaf6', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Ngũ vị hương, bột năng, nước', 1, '', NULL, 'Ngũ vị hương, bột năng, nước', 8);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('b9c920cd-caf3-436c-8d01-af8c98478a11', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Dầu ăn, màu dầu điều, tiêu xay', 1, '', NULL, 'Dầu ăn, màu dầu điều, tiêu xay', 9);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('57686180-7b65-43f3-b3e8-836f022df4ab', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Hạt nêm Aji-ngon® Nấm', 1, '', NULL, 'Hạt nêm Aji-ngon® Nấm', 10);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('b9b33873-5044-4ff4-9b81-302f40283b9a', 'recipe-vit-quay-bac-kinh-chay', NULL, 'Nước tương "Phú Sĩ"', 1, '', NULL, 'Nước tương "Phú Sĩ"', 11);
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-khoai-chien-lac-mayo-me-la-que', 'Khoai chiên lắc mayo mè lá quế', 'Món khoai chiên xốp giòn, lá quế chiên giòn, sốt sệt béo ngọt thơm ngon. Màu vàng hấp dẫn của khoai chiên hòa với màu xốt mayon trắng ngà. Hương thơm béo', 'Sơ chế:
1. Khoai mì, khoai lang, khoai tây gọt vỏ, rửa sạch, để ráo.
2. Cắt khoai thành từng thanh dài khoảng 5cm. Tẩm khoai qua nửa gói Gia vị nêm sẵn Aji-Quick® Bột tẩm khô chiên giòn.
3. Lá quế rửa sạch, để ráo.

Thực hiện:
1. Pha sốt: Cho 2,5M Xốt Mayonnaise Aji-mayo® Vị Nguyên Bản, sữa chua, sữa đặc, 1m mè rang giã nhuyễn vào tô rồi trộn đều lại.
2. Làm bột lắc: Cho 1/3m muối, 1m bột ớt paprika, 1/3m đường, 1/3m tiêu, 1M mè trắng còn lại.
3. Chiên lá quế: Cho dầu nóng già rồi cho lá quế vào chiên đến khi lá quế giòn thì vớt ra để ráo dầu.
4. Chiên khoai: Cho dầu vào chảo, bật bếp ở mức lửa to cho dầu nóng già, sau đó cho khoai vào chiên đến khi khoai vàng giòn.
5. Lắc khoai qua hỗn hợp bột lắc.', 1, 0, 0, 0, 0, NULL, 'Xếp khoai dĩa, rắc lá quế lên trên, rưới sốt mayo mè lên sau đó rắc phần mè rang còn lại lên.
Món ăn ngon đi kèm:Salad cua mì ý', 'Tẩm khoai qua Gia vị nêm sẵn Aji-Quick® Bột tẩm khô chiên giòn giúp khoai có độ giòn, xốp.
Lắc khoai qua hỗn hợp bột lắc giúp tăng hương vị cho khoai.', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('4c9cbd52-df4c-41a5-b506-c88c9556c61d', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Khoai lang Nhật', 100, 'gr', NULL, 'Khoai lang Nhật: 100gr', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3b696a2a-0e9d-4427-8771-60a514295cb0', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Khoai mì', 100, 'gr', NULL, 'Khoai mì: 100gr', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('fef30b63-07c2-48fa-afcb-e7b4fd970fe4', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Khoai Tây', 100, 'gr', NULL, 'Khoai Tây: 100gr', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3c66b5aa-a9b2-4703-905d-101178fd5cca', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Lá quế', 10, 'gr', NULL, 'Lá quế: 10gr', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('94f91bd0-912c-4e1a-9951-a4c88a647ce3', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Sữa chua không đường', 1, 'm', NULL, 'Sữa chua không đường: 1m', 4);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('396f9458-04b4-40e8-937a-55f35c34e911', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Mè trắng rang', 1, 'm (giã nhuyễn', NULL, 'Mè trắng rang: 1m (giã nhuyễn)', 5);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('5ff2f8fa-a984-43fa-8ec6-8b4fd6b5b39a', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Sữa đặc', 1, 'm', NULL, 'Sữa đặc: 1m', 6);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('0ff9cde0-8a04-4e83-a540-eb70875529cc', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Gia vị: Dầu ăn, bột ớt paprika', 1, '', NULL, 'Gia vị: Dầu ăn, bột ớt paprika', 7);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('5cd0170c-f7af-425b-a0a9-6a252a2fc6eb', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Aji-Quick® Bột Tẩm Khô Chiên Giòn', 1, '', NULL, 'Aji-Quick® Bột Tẩm Khô Chiên Giòn', 8);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('db115d67-c09c-4376-98fa-24ebaef19b51', 'recipe-khoai-chien-lac-mayo-me-la-que', NULL, 'Xốt Mayonnaise Aji-mayo® Vị Nguyên Bản', 1, '', NULL, 'Xốt Mayonnaise Aji-mayo® Vị Nguyên Bản', 9);
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-cuon-tau-hu-ky-xot-ro-ti', 'Cuốn tàu hũ ky xốt rô ti', 'Cuốn tàu hũ ky giòn rụm, chấm xốt rô ti mặn ngọt, thơm nồng ngũ vị hương, là món chay mới lạ, đa dạng cho mâm cơm tháng Chạp, ai ăn cũng thích mê.', 'Sơ chế:
1. Đậu hũ chần qua nước sôi vắt ráo, tán nhuyễn. Nấm hương cắt nhỏ.
2. Trộn nhân: cho đậu hũ, nấm hương, cọng ngò rí vào giò sống chay trộn đều, nêm 1/2M tiêu sọ giã bể, 1M hành boaro bằm, 1m Bột ngọt AJI-NO-MO-TO®, 1/2M Hạt nêm Aji-ngon® từ nấm hương và hạt sen.

Thực hiện:
1. Cuốn: Đặt tàu hũ ky lên dĩa, dùng khăn ẩm lau cho mềm, cắt vuông bằng lá rong biển, thoa đều bột bắp lên mặt lá tàu hũ ky, phết một lớp nhân rồi đặt lá rong biển lên, phết tiếp một lớp nhân nữa, gấp hai bên lại rồi cuộn tròn chặt tay.
2. Hấp: cho cuốn tàu hũ ky vào nồi hấp 7 phút, gắp ra để nguội.
3. Chiên: đun nóng dầu, cho cuốn tàu hũ ky vào chiên vàng giòn, vớt ra để nguội.
4. Nấu xốt: phi thơm hành boaro, đổ nước dừa vào, nêm 1/4m Bột ngọt AJI-NO-MO-TO®, 1/3m muối, 1/2m Hạt nêm Aji-ngon® Nấm hương và hạt sen, 1/2m bột ngũ vị hương, 1m tiêu sọ, 1M mật ong, 2m nước tương “Phú Sĩ”, 1m tương ớt, nấu sôi hạ nhỏ lửa. Nấu đến khi thấy xốt sánh sệt, tắt lửa, thêm 1M dầu điều.', 1, 0, 0, 0, 0, NULL, 'Thưởng thức: Cắt cuốn tàu hũ ky thành những khoanh vừa ăn, xếp ra dĩa, rưới xốt và trang trí với lá quế và ớt cắt sợi. Dùng kèm cơm trắng.', 'Hấp cuốn tàu hũ ky trước khi chiên để tạo độ kết dính cho món ăn.
Để mép cuốn tàu hũ ky bên dưới khi hấp không bung.', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('19336a43-79b3-4b10-9b00-027fa476081e', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Lá tàu hũ ky khô', 2, 'lá lớn', NULL, 'Lá tàu hũ ky khô     2 lá lớn', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('de17069e-0f43-4312-ab1e-ed1355fce728', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Giò sống chay', 300, 'g', NULL, 'Giò sống chay      300g', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('37631670-4329-46d3-a493-9d9638c32054', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Đậu hũ trắng', 1, 'miếng lớn', NULL, 'Đậu hũ trắng       1 miếng lớn', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('17e7b348-c61d-44de-9723-db2c8672c7bd', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Nấm hương trắng ngâm mềm', 50, 'g', NULL, 'Nấm hương trắng ngâm mềm    50g', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('9f9bdbe9-857f-48ff-a464-0ce88d033457', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Hành boaro bằm', 50, 'g', NULL, 'Hành boaro bằm     50g', 4);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('86a75674-63c0-437b-b5c5-a1cc83376a4d', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Lá rong biển', 2, 'Lá', NULL, 'Lá rong biển      2 Lá', 5);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('c3a9d8c2-0af2-4c99-ae2e-c727d318a557', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Cọng ngò rí cắt nhỏ', 2, 'M', NULL, 'Cọng ngò rí cắt nhỏ      2M', 6);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('f4f697a5-a8cc-4f35-a271-7c65a5ff3914', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Nước dừa tươi', 2, 'Chén', NULL, 'Nước dừa tươi       2 Chén', 7);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('cd23e604-3c1e-4978-990a-5cdd542abd88', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'RAU NÊM: Lá quế cắt sợi', 1, '', NULL, 'RAU NÊM: Lá quế cắt sợi', 8);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('96135469-34cb-435a-b83d-017d92e9cdf5', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'ĂN KÈM: Cơm trắng', 1, '', NULL, 'ĂN KÈM: Cơm trắng', 9);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('62cb9443-3fe9-44a6-a0a1-202b8e2ffd14', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Gia vị: Tiêu sọ giã bể, muối, bột ngũ vị hương, bột bắp, mật ong, tương ớt, dầu ăn, dầu điều', 1, '', NULL, 'Gia vị: Tiêu sọ giã bể, muối, bột ngũ vị hương, bột bắp, mật ong, tương ớt, dầu ăn, dầu điều', 10);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('cd28d8e9-9933-4b58-8bec-130eed288880', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Nước tương "Phú Sĩ"', 1, '', NULL, 'Nước tương "Phú Sĩ"', 11);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('4df42c90-60a0-48eb-a10f-67d109a70cba', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Bột ngọt AJI-NO-MOTO®', 1, '', NULL, 'Bột ngọt AJI-NO-MOTO®', 12);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('d21c61ea-9805-4c89-ab19-339bed8f33c8', 'recipe-cuon-tau-hu-ky-xot-ro-ti', NULL, 'Hạt nêm Aji-ngon® Nấm', 1, '', NULL, 'Hạt nêm Aji-ngon® Nấm', 13);
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-lau-ca-lang-mang-chua', 'Lẩu cá lăng măng chua', 'Những bữa ăn ngày cuối năm luôn đầm ấm với người thân sum họp quây quần, sẽ còn gì ngon lành và ấm áp hơn bằng việc cả nhà ngồi vây quanh nồi lẩu, nếm từng', 'Sơ chế:
1. Cá lăng cắt khúc dày 1.5cm, chần qua nước sôi có ít gừng. Sả băm nhỏ.
2. Măng chua rửa sạch, vắt ráo. Cà chua cắt múi cau. Thơm cắt miếng mỏng. Rau om, ngò gai cắt khúc 2cm. Ớt cắt lát.

Thực hiện:
1. Phi thơm sả, ớt hiểm, hành tỏi băm với 1/2 chén dầu ăn (~7M), cho cá vào xốc săn, trút ra dĩa, rồi thêm cà chua, thơm, nêm 1M muối, 1M đường, cho măng chua và 1.5 lít nước, đun sôi, nêm 1 gói Aji-Quick® Gia vị nêm sẵn Lẩu Thái và 1M đường khuấy đều, cho cá vào lại nước lẩu, nấu thêm 1 lúc cho cá chín, cho rau om, ngò gai vào.', 1, 0, 0, 0, 0, NULL, 'Ăn kèm bún, chấm cá với nước mắm và ớt cắt lát.', 'Xốc cá trước với hành tỏi băm và sả giúp cá tăng hương vị.
Xào cà chua, thơm và măng chua trước với hành tỏi và sả băm rồi mới cho cá vào giúp khử được mùi tanh của cá', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('23cd2c86-f6af-480a-baa2-ce3bd79b9165', 'recipe-lau-ca-lang-mang-chua', NULL, 'Cá lăng', 500, 'gr', NULL, 'Cá lăng : 500gr', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('c1c3d7e5-376a-4577-a39f-3beacfa26fb4', 'recipe-lau-ca-lang-mang-chua', NULL, 'Măng chua', 300, 'gr', NULL, 'Măng chua : 300gr', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3258c1f4-b79a-45b9-a8ed-8cf4f6603942', 'recipe-lau-ca-lang-mang-chua', NULL, 'Cà chua', 2, 'trái', NULL, 'Cà chua : 2 trái', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('7556a8d8-7a98-4f62-a635-f52fbb8a0c36', 'recipe-lau-ca-lang-mang-chua', NULL, 'Thơm : 1/4trái', 1, '', NULL, 'Thơm :  1/4trái', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('9e844669-8655-4847-b135-a85eaf977d34', 'recipe-lau-ca-lang-mang-chua', NULL, 'Bún tươi', 500, 'gr', NULL, 'Bún tươi : 500gr', 4);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('eb3be219-71f8-4e1d-ac3f-8cc29ce4eaf8', 'recipe-lau-ca-lang-mang-chua', NULL, 'Hành tím băm', 1, 'M', NULL, 'Hành tím băm :  1M', 5);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3d794027-42f0-4216-8934-5e4e8c27a086', 'recipe-lau-ca-lang-mang-chua', NULL, 'Tỏi băm', 1, 'M', NULL, 'Tỏi băm : 1M', 6);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('298e5523-079a-47e9-b9b1-d4d042705a13', 'recipe-lau-ca-lang-mang-chua', NULL, 'Rau om', 3, 'cây', NULL, 'Rau om : 3 cây', 7);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('ac26f455-268b-4c62-8ac9-9c8698783d78', 'recipe-lau-ca-lang-mang-chua', NULL, 'Ngò gai', 3, 'cây', NULL, 'Ngò gai : 3 cây', 8);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('c0948cba-17b2-4282-a033-81563a38daa1', 'recipe-lau-ca-lang-mang-chua', NULL, 'Ớt hiểm', 1, 'trái', NULL, 'Ớt hiểm : 1 trái', 9);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('18361785-444c-47bd-b5e9-1d307ecce0ad', 'recipe-lau-ca-lang-mang-chua', NULL, 'Gừng tươi, sả', 1, '', NULL, 'Gừng tươi, sả', 10);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('73e960ad-b7d7-4219-8089-6a559b33e76d', 'recipe-lau-ca-lang-mang-chua', NULL, 'Dầu ăn, nước mắm, đường, muối', 1, '', NULL, 'Dầu ăn, nước mắm, đường, muối', 11);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('43b4372f-343d-4147-bd36-d3f22ac9c9f5', 'recipe-lau-ca-lang-mang-chua', NULL, 'Gia vị nêm sẵn Aji-Quick® Lẩu Thái', 1, '', NULL, 'Gia vị nêm sẵn Aji-Quick® Lẩu Thái', 12);
INSERT INTO meal_recipes (id, name, description, instructions, servings, calories_per_serving, protein_g, fat_g, carb_g, goal_tags, serving_notes, tips, expert_advice, suggested_combo, created_at, updated_at) VALUES ('recipe-nguu-bang-xao-hai-san', 'Ngưu bàng xào hải sản', 'Ngưu bàng xào hải sản, củ ngưu bàng ngọt thanh, giàu kiềm dương, kết hợp rau củ, giấm, món ăn tốt cho sức khỏe, hỗ trợ người bệnh và người dư acid.', 'Sơ chế:
1. Ngưu bàng rửa sạch, cắt sợi nhỏ 3 ly, trộn với 1.5M giấm, 1m hạt nêm Aji-ngon®. Cà rốt cắt sợi. Giá rửa sạch. Hẹ lá cắt ngắn khoảng 3cm.
2. Tôm chẻ lưng, mực cắt sợi, ướp tôm và mực với 1/2M hành tỏi băm, 1/4m tiêu, 1/2m hạt nêm Aji-ngon để thấm. Trước khi xào, trộn với 1m bột năng.

Thực hiện:
1. Xào: Phi thơm 1/2M hành tỏi băm, cho hải sản vào xào nhanh lửa lớn để hải sản săn lại, trút ra dĩa. Tiếp tục phi thơm hành tỏi băm, cho cà rốt và ngưu bàng vào xào với 3M nước, 1/2m đường, xào ngưu bàng mềm thì cho hải sản, giá và hẹ vào, nêm 1m dầu hào, 1/2m dầu mè, xào rau củ vừa chín thì tắt lửa, rắc 1 chút tiêu sau cùng.', 1, 0, 0, 0, 0, NULL, 'Trình bày: Cho ngưu bàng xào hải sản ra dĩa, rắc mè rang, trang trí với ngò rí và ớt sừng sợi, dùng kèm nước tương “Phú Sĩ” và ớt cắt lát.', 'Ngưu bàng trộn với giấm để khi xào giữ được màu trắng và chất dinh dưỡng.
Khi xào thêm nước để ngưu bàng chín mềm.', NULL, NULL, '2026-08-07T22:02:58.523Z', '2026-08-07T22:02:58.523Z');
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('b713e27d-3961-4a13-9d7c-5572e6144111', 'recipe-nguu-bang-xao-hai-san', NULL, 'Ngưu bàng (Gô bô)', 150, 'g', NULL, 'Ngưu bàng (Gô bô)   150g', 0);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('abc7a641-f8ff-4c4a-b52c-cca41ce5b002', 'recipe-nguu-bang-xao-hai-san', NULL, 'Cà rốt', 50, 'g', NULL, 'Cà rốt     50g', 1);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('69ca02f1-defc-4414-a494-001983c338a3', 'recipe-nguu-bang-xao-hai-san', NULL, 'Tôm sú bóc vỏ chừa đuôi', 100, 'g', NULL, 'Tôm sú bóc vỏ chừa đuôi  100g', 2);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('1dea6673-de1a-4692-82dc-e37c97614268', 'recipe-nguu-bang-xao-hai-san', NULL, 'Mực', 100, 'g', NULL, 'Mực     100g', 3);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('58216ec5-387d-42c7-8fd5-56e809a29563', 'recipe-nguu-bang-xao-hai-san', NULL, 'Giá', 100, 'g', NULL, 'Giá     100g', 4);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('5eac14ab-0db2-47bc-b688-b5cbb1b26c54', 'recipe-nguu-bang-xao-hai-san', NULL, 'Hẹ lá', 50, 'g', NULL, 'Hẹ lá     50g', 5);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('36ae9172-f45d-44d5-96ec-10355ac3ca95', 'recipe-nguu-bang-xao-hai-san', NULL, 'Hành tỏi băm', 2, 'M', NULL, 'Hành tỏi băm    2M', 6);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('58e04818-c2f1-4d44-9758-00f4f7950ea7', 'recipe-nguu-bang-xao-hai-san', NULL, 'Mè rang', 1, 'M', NULL, 'Mè rang    1M', 7);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('c2a993d8-2a93-4020-a0d5-84b446c67347', 'recipe-nguu-bang-xao-hai-san', NULL, 'RAU NÊM: ớt sừng sợi, ngò rí, ớt cắt lát', 1, '', NULL, 'RAU NÊM: ớt sừng sợi, ngò rí, ớt cắt lát', 8);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('3099681f-e93e-497a-92c6-c3fe39317e28', 'recipe-nguu-bang-xao-hai-san', NULL, 'ĂN KÈM: Cơm', 1, '', NULL, 'ĂN KÈM: Cơm', 9);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('c29f104d-49dd-40eb-acf6-5c567be6794a', 'recipe-nguu-bang-xao-hai-san', NULL, 'Gia vị: dầu mè, tiêu, dầu ăn, dầu hào, bột năng, đường', 1, '', NULL, 'Gia vị: dầu mè, tiêu, dầu ăn, dầu hào, bột năng, đường', 10);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('2fe4abd7-e5b6-4a2e-bc0f-692d01a3444c', 'recipe-nguu-bang-xao-hai-san', NULL, 'Hạt nêm Aji-ngon® Heo', 1, '', NULL, 'Hạt nêm Aji-ngon® Heo', 11);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('8342bdc2-cf4d-4644-9e49-036f0ac76cc0', 'recipe-nguu-bang-xao-hai-san', NULL, 'Nước tương "Phú Sĩ"', 1, '', NULL, 'Nước tương "Phú Sĩ"', 12);
INSERT INTO meal_recipe_ingredients (id, recipe_id, food_id, name, quantity, unit, note, raw_text, sort_order) VALUES ('8ddc6e90-3779-40a8-87dc-cbf99f8653ac', 'recipe-nguu-bang-xao-hai-san', NULL, '"AJINOMOTO" Giấm gạo lên men', 1, '', NULL, '"AJINOMOTO" Giấm gạo lên men', 13);
