// Curated icon set for all dynamic-by-name icon lookups in the app (tool/category
// icons from the DB and static registries, admin nav icons). `import * as Icons
// from "lucide-react"` pulls the entire ~1000-icon library into the server bundle
// since these lookups are dynamic — this named-import map keeps only what's used.
import {
  AlignLeft,
  Asterisk,
  Binary,
  Box,
  Braces,
  Briefcase,
  Calendar,
  CalendarClock,
  ChevronDown,
  Circle,
  Clock,
  Code,
  Code2,
  Database,
  Dices,
  FileArchive,
  FileText,
  Fingerprint,
  FolderTree,
  Frame,
  Hash,
  Image,
  ImageIcon,
  Keyboard,
  KeyRound,
  LayoutDashboard,
  Link,
  Link2,
  ListChecks,
  ListMusic,
  Music2,
  Newspaper,
  Palette,
  QrCode,
  Repeat,
  Rss,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Tags,
  Timer,
  Toolbox,
  Type,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  AlignLeft,
  Asterisk,
  Binary,
  Box,
  Braces,
  Briefcase,
  Calendar,
  CalendarClock,
  ChevronDown,
  Circle,
  Clock,
  Code,
  Code2,
  Database,
  Dices,
  FileArchive,
  FileText,
  Fingerprint,
  FolderTree,
  Frame,
  Hash,
  Image,
  ImageIcon,
  Keyboard,
  KeyRound,
  LayoutDashboard,
  Link,
  Link2,
  ListChecks,
  ListMusic,
  Music2,
  Newspaper,
  Palette,
  QrCode,
  Repeat,
  Rss,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Tags,
  Timer,
  Toolbox,
  Type,
  Users,
  Wallet,
  Wrench,
};

export function getIcon(name: string | undefined, fallback: LucideIcon = Box): LucideIcon {
  return (name && iconMap[name]) || fallback;
}
