import type { Category, Tool } from "@/types/tool";

export const CATEGORIES: Category[] = [
  { id: "media", name: "Media & Images", sortOrder: 1 },
  { id: "text", name: "Text & Writing", sortOrder: 2 },
  { id: "utility", name: "Utilities", sortOrder: 3 },
];

export const TOOLS: Tool[] = [
  {
    id: "t1",
    slug: "genqr",
    name: "QR Codes",
    description: "Generate custom QR codes for links, wifi, business cards.",
    subdomain: "genqr.core47.xyz",
    icon: "QrCode",
    categoryId: "utility",
    status: "active",
    sortOrder: 1,
  },
  {
    id: "t2",
    slug: "beautysql",
    name: "BeautySQL",
    description: "Format and beautify your SQL queries right in the browser.",
    subdomain: "beautysql.core47.xyz",
    icon: "Code2",
    categoryId: "utility",
    status: "active",
    sortOrder: 2,
  },
  {
    id: "t3",
    slug: "shortlink",
    name: "Link Shortener",
    description: "Free link shortener with basic click analytics.",
    subdomain: "shortlink.core47.xyz",
    icon: "Link",
    categoryId: "utility",
    status: "active",
    sortOrder: 3,
  },
  {
    id: "t4",
    slug: "bio",
    name: "Bio Pages",
    description: "Gather all your links into a single bio page.",
    subdomain: "bio.core47.xyz",
    icon: "FileText",
    categoryId: "text",
    status: "beta",
    sortOrder: 4,
  },
  {
    id: "t5",
    slug: "editimg",
    name: "Online Image Editor",
    description: "Edit images quickly, right in the browser.",
    subdomain: "editimg.core47.xyz",
    icon: "Image",
    categoryId: "media",
    status: "active",
    sortOrder: 5,
  },
  {
    id: "t6",
    slug: "frame",
    name: "Frame Avatar",
    description: "Generate a PNG avatar frame for a campaign.",
    subdomain: "frame.core47.xyz",
    icon: "Frame",
    categoryId: "media",
    status: "soon",
    sortOrder: 6,
  },
];
