import type { Category, Tool } from "@/types/tool";

export const CATEGORIES: Category[] = [
  { id: "media", name: "Media & Ảnh", sortOrder: 1 },
  { id: "text", name: "Văn bản & Chữ", sortOrder: 2 },
  { id: "utility", name: "Tiện ích", sortOrder: 3 },
];

export const TOOLS: Tool[] = [
  {
    id: "t1",
    slug: "genqr",
    name: "QR Codes",
    description: "Tạo mã QR tùy chỉnh cho liên kết, wifi, danh thiếp.",
    subdomain: "genqr.core47.xyz",
    icon: "QrCode",
    categoryId: "utility",
    status: "active",
    sortOrder: 1,
  },
  {
    id: "t2",
    slug: "beautysql",
    name: "BeautySQL",
    description: "Format & làm đẹp câu lệnh SQL của bạn ngay trên trình duyệt.",
    subdomain: "beautysql.core47.xyz",
    icon: "Code2",
    categoryId: "utility",
    status: "active",
    sortOrder: 2,
  },
  {
    id: "t3",
    slug: "shortlink",
    name: "Rút gọn link",
    description: "Công cụ rút gọn link miễn phí, thống kê click cơ bản.",
    subdomain: "shortlink.core47.xyz",
    icon: "Link",
    categoryId: "utility",
    status: "active",
    sortOrder: 3,
  },
  {
    id: "t4",
    slug: "bio",
    name: "Bio Pages",
    description: "Gom mọi liên kết của bạn vào một trang tiểu sử duy nhất.",
    subdomain: "bio.core47.xyz",
    icon: "FileText",
    categoryId: "text",
    status: "beta",
    sortOrder: 4,
  },
  {
    id: "t5",
    slug: "editimg",
    name: "Sửa ảnh Online",
    description: "Chỉnh sửa ảnh trực tuyến nhanh chóng ngay trên trình duyệt.",
    subdomain: "editimg.core47.xyz",
    icon: "Image",
    categoryId: "media",
    status: "active",
    sortOrder: 5,
  },
  {
    id: "t6",
    slug: "frame",
    name: "Frame Avatar",
    description: "Tạo khung frame ảnh đại diện dạng PNG cho chiến dịch.",
    subdomain: "frame.core47.xyz",
    icon: "Frame",
    categoryId: "media",
    status: "soon",
    sortOrder: 6,
  },
];